services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: exchange_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"